"""rename address

Revision ID: 155504fa1232
Revises: 4fd9d10a2185
Create Date: 2024-01-09 14:24:38.281991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "155504fa1232"
down_revision = "4fd9d10a2185"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "address", new_column_name="location")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("departments", "location", new_column_name="address")
    # ### end Alembic commands ###
