"""rename department

Revision ID: 4fd9d10a2185
Revises: 45d1350750c3
Create Date: 2024-01-09 14:21:56.121579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4fd9d10a2185"
down_revision = "45d1350750c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("department", "departments")
    # ### end Alembic commands ###
